node_js: stable
sudo: required
dist: trusty
addons:
  sauce_connect: false
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
bnode_js:
  - "node"
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
